/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v0/projects": {
    /**
     * Get All Projects
     * @description Get a list of projects for this organization
     *
     * Returns:
     *     a list of requested projects
     */
    get: operations["get_all_projects_v0_projects_get"];
    /**
     * Create Project
     * @description Create a project
     *
     * Returns:
     *     the id, name, and tags for the created project
     */
    post: operations["create_project_v0_projects_post"];
  };
  "/v0/projects/{project_id}": {
    /**
     * Get Project
     * @description Get a project
     *
     * Returns:
     *     the requested project
     */
    get: operations["get_project_v0_projects__project_id__get"];
    /**
     * Update Project
     * @description Update a project
     *
     * Returns:
     *     the requested project
     */
    put: operations["update_project_v0_projects__project_id__put"];
  };
  "/v0/scenario_sets": {
    /**
     * Get Scenario Sets
     * @description Find all scenario sets based on either the project id or the scenario id
     *
     * Returns:
     *     a list of scenario sets (project id) or a list of scenarios (scenario id)
     */
    get: operations["get_scenario_sets_v0_scenario_sets_get"];
    /**
     * Create Scenario Set
     * @description Triggers a generation of a test scenario set, could be long running.
     * This scenario set can now be used for testing on a model.
     *
     * Returns:
     *     Object: generation result with '201 Created' status code on success.
     */
    post: operations["create_scenario_set_v0_scenario_sets_post"];
  };
  "/v0/scenario_sets/{scenario_id}": {
    /**
     * Update Scenario Set
     * @description Update a Scenario Set
     *
     * Returns:
     *     the updated Scenario Set
     */
    put: operations["update_scenario_set_v0_scenario_sets__scenario_id__put"];
    /**
     * Delete Scenario Set
     * @description Deletes the scenario set and cascades deletes to all related entities.
     * Namely, Evaluations, Evaluation Datapoints, and  Model Datapoints
     *
     * !! Use With Caution !!
     *
     * Raises:
     *     HTTPException: 404 if scenario_id is not found
     *
     * Returns: 204 status code on successful deletion
     */
    delete: operations["delete_scenario_set_v0_scenario_sets__scenario_id__delete"];
  };
  "/v0/scenario_sets_upload": {
    /**
     * Scenario Sets Upload
     * @description Upload new scenarios
     *
     * Returns:
     *     the Scenario Set with the uploaded scenarios
     */
    post: operations["scenario_sets_upload_v0_scenario_sets_upload_post"];
  };
  "/v0/scenario_sets_download/{scenario_id}": {
    /**
     * Get Scenario Sets Download
     * @description Get the scenario set for a particular scenario ID
     *
     * Returns:
     *     a list of scenarios
     */
    get: operations["get_scenario_sets_download_v0_scenario_sets_download__scenario_id__get"];
  };
  "/v0/scenario_data_points/{scenario_id}": {
    /**
     * Get Scenario Set Data Points
     * @description Get all scenarios datapoints
     *
     * Returns:
     *     a list of scenario datapoints
     */
    get: operations["get_scenario_set_data_points_v0_scenario_data_points__scenario_id__get"];
  };
  "/v0/scenario_sets_generate": {
    /**
     * Generate Scenario Set
     * @description Triggers a generation of a scenario set based on source scenario ID, could be long running.
     * A registered model can now use this scenario set for testing.
     *
     * Returns:
     *     Object: generation result with '201 Created' status code on success.
     */
    post: operations["generate_scenario_set_v0_scenario_sets_generate_post"];
  };
  "/v0/find_datapoints": {
    /**
     * Get Datapoints
     * @description gets all the datapoints created by a given token.
     *
     * Returns:
     *     list: An array of datapoint objects.
     */
    post: operations["get_datapoints_v0_find_datapoints_post"];
  };
  "/v0/datapoints": {
    /**
     * Add Datapoint
     * @description Add a datapoint for a particular registered model
     *
     * Returns:
     *     Empty ressponse with 201 status code on success.
     */
    post: operations["add_datapoint_v0_datapoints_post"];
  };
  "/v0/register_model": {
    /**
     * Register Model
     * @description Register a model for testing. This model can then be tested using a scenario set.
     *
     * Returns:
     *     the id of the registered model
     */
    post: operations["register_model_v0_register_model_post"];
  };
  "/v0/models_under_test/{mut_id}": {
    /**
     * Get Model Under Test
     * @description Get a model under test
     *
     * Returns:
     *     the requested model under test
     */
    get: operations["get_model_under_test_v0_models_under_test__mut_id__get"];
    /**
     * Update Model Under Test
     * @description Update a model under test
     *
     * Returns:
     *     the updated model under test
     */
    put: operations["update_model_under_test_v0_models_under_test__mut_id__put"];
  };
  "/v0/models_under_test": {
    /**
     * Get All Models Under Test
     * @description Get a list of models under test for this organization
     *
     * Returns:
     *     a list of requested models under test
     */
    get: operations["get_all_models_under_test_v0_models_under_test_get"];
  };
  "/v0/get_semantic_overlap": {
    /** Get Semantic Overlap */
    post: operations["get_semantic_overlap_v0_get_semantic_overlap_post"];
  };
  "/v0/find_test_runs": {
    /**
     * Find Test Run
     * @description Find Test Runs
     *
     * Returns:
     *     a list of Test Runs
     */
    post: operations["find_test_run_v0_find_test_runs_post"];
  };
  "/v0/test_runs/{test_run_id}": {
    /**
     * Get Test Run
     * @description Get a Test Run
     *
     * Returns:
     *     the Test Run
     */
    get: operations["get_test_run_v0_test_runs__test_run_id__get"];
    /**
     * Update Test Run
     * @description Update a Test Run
     * Returns:
     *     the updated Test Run
     */
    put: operations["update_test_run_v0_test_runs__test_run_id__put"];
  };
  "/v0/test_run": {
    /**
     * Run Test
     * @description Runs tests on a model (mut_id) using previously generated scenario.
     * Feeds the scenario data (scenario_id) into the model and evaulates results
     * depending on the test type specified.
     *
     * Returns:
     *     The test run data which includes the evaluated metrics from the run.
     */
    post: operations["run_test_v0_test_run_post"];
  };
  "/v0/test_data_point": {
    /**
     * Add Test Data Point
     * @description Add a test run metric
     *
     * Returns:
     *     The persisted test run metric item
     */
    post: operations["add_test_data_point_v0_test_data_point_post"];
  };
  "/v0/test_data_points/{test_data_point_id}": {
    /**
     * Get Test Data Point
     * @description Get a Test Run
     *
     * Returns:
     *     the Test Run
     */
    get: operations["get_test_data_point_v0_test_data_points__test_data_point_id__get"];
  };
  "/v0/find_test_data_points": {
    /**
     * Find Test Data Points
     * @description Find Test Data Point
     *
     * Returns:
     *     a list of Test Data Points
     */
    post: operations["find_test_data_points_v0_find_test_data_points_post"];
  };
}

export type webhooks = any;

export interface components {
  schemas: {
    /** Body_scenario_sets_upload_v0_scenario_sets_upload_post */
    Body_scenario_sets_upload_v0_scenario_sets_upload_post: {
      /**
       * Project Id
       * Format: uuid
       * @description Project ID or None for default project
       */
      project_id?: string;
      /**
       * Name
       * @description Name of the Scenario Set
       */
      name: string;
      /**
       * File
       * Format: binary
       */
      file?: string;
    };
    /** DatapointListItem */
    DatapointListItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Tags
       * @default []
       */
      tags?: string[];
      /** Input */
      input?: any | unknown[] | string;
      /**
       * Input Datetime
       * Format: date-time
       */
      input_datetime?: string;
      /** Result */
      result?: any | unknown[] | string;
      /**
       * Result Datetime
       * Format: date-time
       */
      result_datetime?: string;
      /** Feedback */
      feedback?: number;
      /** Error Message */
      error_message?: string;
      /** Error Code */
      error_code?: string;
      /**
       * Time Created
       * Format: date-time
       */
      time_created?: string;
      /** Context Token */
      context_token?: string;
      /**
       * Mut Id
       * Format: uuid
       */
      mut_id?: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id?: string;
      /**
       * Test Run Id
       * Format: uuid
       */
      test_run_id?: string;
    };
    /** DatapointResponse */
    DatapointResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id?: string;
      /**
       * Mut Id
       * Format: uuid
       */
      mut_id?: string;
    };
    /** DatapointSchema */
    DatapointSchema: {
      /**
       * Mut Id
       * Format: uuid
       * @description Model ID
       */
      mut_id?: string;
      /**
       * Input
       * Format: json-string
       * @description Inputted value into the model
       */
      input?: string;
      /**
       * Input Datetime
       * Format: date-time
       * @description Datetime for the input
       */
      input_datetime?: string;
      /**
       * Result
       * Format: json-string
       * @description Outputted value from the model based on the input
       */
      result?: string;
      /**
       * Result Datetime
       * Format: date-time
       * @description Datetime for the result
       */
      result_datetime?: string;
      /**
       * Tags
       * @description Tags are strings that can be used to filter datapoints in the Okareo app
       * @default []
       */
      tags?: string[];
      /**
       * Feedback
       * @description Feedback is a 0 to 1 float value that captures user feedback range for related datapoint results
       */
      feedback?: number;
      /** Error Message */
      error_message?: string;
      /** Error Code */
      error_code?: string;
      /**
       * Context Token
       * @description Context token is a unique token to link various datapoints which originate from the same context
       */
      context_token?: string;
      /**
       * Test Run Id
       * Format: uuid
       * @description ID of testrun
       */
      test_run_id?: string;
    };
    /** DatapointSearch */
    DatapointSearch: {
      /**
       * Tags
       * @description Tags are strings that can be used to filter datapoints in the Okareo app
       * @default []
       */
      tags?: string[];
      /**
       * From Date
       * Format: date-time
       * @description Earliest date
       * @default 2022-12-31T23:59:59.999999
       */
      from_date?: string;
      /**
       * To Date
       * Format: date-time
       * @description Latest date
       */
      to_date?: string;
      /**
       * Feedback
       * @description Feedback is a 0 to 1 float value that captures user feedback range for related datapoint results
       */
      feedback?: number;
      /** Error Code */
      error_code?: string;
      /**
       * Context Token
       * @description Context token is a unique token to link various datapoints which originate from the same context
       */
      context_token?: string;
      /**
       * Project Id
       * @description Project ID
       */
      project_id?: string;
      /**
       * Mut Id
       * Format: uuid
       * @description Model ID
       */
      mut_id?: string;
      /**
       * Test Run Id
       * Format: uuid
       * @description Test run ID
       */
      test_run_id?: string;
    };
    /** ErrorResponse */
    ErrorResponse: {
      /** Detail */
      detail: string;
    };
    /** FindTestDataPointPayload */
    FindTestDataPointPayload: {
      /**
       * Id
       * Format: uuid
       * @description ID of the datapoint
       */
      id?: string;
      /**
       * Test Run Id
       * Format: uuid
       * @description ID of the test run
       */
      test_run_id?: string;
      /**
       * Scenario Data Point Id
       * Format: uuid
       * @description ID of the scenario data point
       */
      scenario_data_point_id?: string;
      /** Metric Type */
      metric_type?: string;
    };
    /** GeneralFindPayload */
    GeneralFindPayload: {
      /**
       * Id
       * Format: uuid
       * @description ID for the testrun
       */
      id?: string;
      /**
       * Project Id
       * Format: uuid
       * @description ID for the project
       */
      project_id?: string;
      /**
       * Mut Id
       * Format: uuid
       * @description ID of the model
       */
      mut_id?: string;
      /**
       * Scenario Set Id
       * Format: uuid
       * @description ID of the scenario set
       */
      scenario_set_id?: string;
      /**
       * Tags
       * @description Tags are strings that can be used to filter test runs in the Okareo app
       * @default []
       */
      tags?: string[];
    };
    /**
     * GenerationTone
     * @description An enumeration.
     * @enum {unknown}
     */
    GenerationTone: "Neutral" | "Formal" | "Informal" | "Persuasive" | "Empathetic";
    /** ModelUnderTestResponse */
    ModelUnderTestResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Name */
      name: string;
      /** Tags */
      tags: string[];
      /** Time Created */
      time_created: string;
      /** Datapoint Count */
      datapoint_count?: number;
      /**
       * App Link
       * @description This URL links to the Okareo webpage for this model
       * @default
       */
      app_link?: string;
    };
    /** ModelUnderTestSchema */
    ModelUnderTestSchema: {
      /**
       * Name
       * @description Name of the model
       */
      name?: string;
      /**
       * Models
       * @description Models to be added for testing
       */
      models?: {
        [key: string]: any;
      };
      /**
       * Tags
       * @description Tags are strings that can be used to filter models in the Okareo app
       * @default []
       */
      tags?: string[];
      /**
       * Project Id
       * Format: uuid
       * @description ID of the project
       */
      project_id?: string;
    };
    /** ProjectResponse */
    ProjectResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /**
       * Tags
       * @default []
       */
      tags?: string[];
    };
    /** ProjectSchema */
    ProjectSchema: {
      /**
       * Name
       * @description Name of the project
       */
      name?: string;
      /**
       * Tags
       * @description Tags are strings that can be used to filter projects in the Okareo app
       * @default []
       */
      tags?: string[];
    };
    /** ScenarioDataPoinResponse */
    ScenarioDataPoinResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Input */
      input: any | unknown[] | string;
      /** Result */
      result: any | unknown[] | string;
      /**
       * Meta Data
       * Format: json-string
       */
      meta_data?: string;
    };
    /** ScenarioSetCreate */
    ScenarioSetCreate: {
      /**
       * Project Id
       * Format: uuid
       * @description ID for the project
       */
      project_id?: string;
      /**
       * Name
       * @description Name of the scenario set
       */
      name: string;
      /**
       * Seed Data
       * @description Seed data is a list of dictionaries, each with an input and result
       */
      seed_data: components["schemas"]["SeedData"][];
      /**
       * Number Examples
       * @description Number of examples
       */
      number_examples: number;
      /**
       * @description Type of generation. Current supported scenario types are:<br />
       *         Seed: Seed data for a scenario set<br />
       *         Rephrase invariant: Results will be rephrased versions of inputs<br />
       *         Conditional: Results will be rephrased inputs represented in a conditional format<br />
       *         Text reverse question: The result will be the target question for the input<br />
       *         Text reverse label: The result will be the intent of the target question for the input
       * @default SEED
       */
      generation_type?: components["schemas"]["ScenarioType"];
      /**
       * @description Tone to use for scenario generation.
       * @default Neutral
       */
      generation_tone?: components["schemas"]["GenerationTone"];
    };
    /** ScenarioSetGenerate */
    ScenarioSetGenerate: {
      /**
       * Project Id
       * Format: uuid
       * @description ID for the project
       */
      project_id?: string;
      /**
       * Source Scenario Id
       * Format: uuid
       * @description ID for the scenario set that the generated scenario set will use as a source
       */
      source_scenario_id: string;
      /**
       * Name
       * @description Name of the generated scenario set
       */
      name: string;
      /**
       * Number Examples
       * @description Number of examples to be generated for the scenario set
       */
      number_examples: number;
      /**
       * @description Type of generation. Current supported scenario types are:<br />
       *         Seed: Seed data for a scenario set<br />
       *         Rephrase invariant: Results will be rephrased versions of inputs<br />
       *         Conditional: Results will be rephrased inputs represented in a conditional format<br />
       *         Text reverse question: The result will be the target question for the input<br />
       *         Text reverse label: The result will be the intent of the target question for the input
       * @default REPHRASE_INVARIANT
       */
      generation_type?: components["schemas"]["ScenarioType"];
      /**
       * @description Tone to use for scenario generation.
       * @default Neutral
       */
      generation_tone?: components["schemas"]["GenerationTone"];
    };
    /** ScenarioSetResponse */
    ScenarioSetResponse: {
      /**
       * Scenario Id
       * Format: uuid
       */
      scenario_id: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /**
       * Time Created
       * Format: date-time
       */
      time_created: string;
      /** Type */
      type: string;
      /**
       * Tags
       * @default []
       */
      tags?: string[];
      /** Name */
      name?: string;
      /**
       * Seed Data
       * @default []
       */
      seed_data?: components["schemas"]["SeedData"][];
      /**
       * Scenario Count
       * @default 0
       */
      scenario_count?: number;
      /**
       * Scenario Input
       * @default []
       */
      scenario_input?: string[];
      /**
       * App Link
       * @description This URL links to the Okareo webpage for this scenario set
       * @default
       */
      app_link?: string;
    };
    /** ScenarioSetUpdate */
    ScenarioSetUpdate: {
      /**
       * Project Id
       * Format: uuid
       * @description ID for the project
       */
      project_id?: string;
      /**
       * Time Created
       * Format: date-time
       */
      time_created?: string;
      /**
       * Type
       * @description Generation type of scenario
       */
      type?: string;
      /**
       * Tags
       * @description Tags are strings that can be used to filter scenario sets in the Okareo app
       * @default []
       */
      tags?: string[];
      /**
       * Name
       * @description Name of the scenario set
       */
      name?: string;
      /**
       * Seed Data
       * @description Seed data is a list of dictionaries, each with an input and result
       * @default []
       */
      seed_data?: components["schemas"]["SeedData"][];
      /**
       * Scenario Input
       * @default []
       */
      scenario_input?: string[];
    };
    /**
     * ScenarioType
     * @description An enumeration.
     * @enum {unknown}
     */
    ScenarioType: "SEED" | "REPHRASE_INVARIANT" | "CONDITIONAL" | "TEXT_REVERSE_QUESTION" | "TEXT_REVERSE_LABELED" | "TERM_RELEVANCE_INVARIANT" | "COMMON_CONTRACTIONS" | "COMMON_MISSPELLINGS" | "WORD_INFLECTIONS" | "WORD_QWERTY_MISSPELL" | "WORD_CHARACTER_INSERTION" | "WORD_SYNONYM_EMBEDDING" | "LABEL_REVERSE_INVARIANT" | "ROUNDTRIP_INVARIANT" | "NEGATION" | "NAMED_ENTITY_SUBSTITUTION";
    /** SeedData */
    SeedData: {
      /** Input */
      input: string;
      /** Result */
      result: string | string[];
    };
    /** SemanticPayload */
    SemanticPayload: {
      /** Source Text */
      source_text: string;
      /** Output Text */
      output_text: string;
    };
    /** SemanticResult */
    SemanticResult: {
      /** Document Sentences */
      document_sentences: string[];
      /** Summary Sentences */
      summary_sentences: string[];
      /** Scores */
      scores: string[][];
    };
    /** TestDataPointItem */
    TestDataPointItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Scenario Data Point Id
       * Format: uuid
       */
      scenario_data_point_id: string;
      /**
       * Test Run Id
       * Format: uuid
       */
      test_run_id: string;
      /** Metric Type */
      metric_type: string;
      /** Metric Value */
      metric_value: any;
    };
    /** TestDataPointPayload */
    TestDataPointPayload: {
      /**
       * Test Run Id
       * Format: uuid
       * @description ID for the testrun
       */
      test_run_id?: string;
      /**
       * Scenario Data Point Id
       * Format: uuid
       * @description ID of the scenario data point
       */
      scenario_data_point_id?: string;
      /** Metric Type */
      metric_type?: string;
      /**
       * Metric Value
       * Format: json-string
       */
      metric_value?: string;
    };
    /** TestDataPointResponse */
    TestDataPointResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** TestRunItem */
    TestRunItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /**
       * Mut Id
       * Format: uuid
       */
      mut_id: string;
      /**
       * Scenario Set Id
       * Format: uuid
       */
      scenario_set_id: string;
      /** Name */
      name?: string;
      /**
       * Tags
       * @default []
       */
      tags?: string[];
      /** Type */
      type?: string;
      /**
       * Start Time
       * Format: date-time
       */
      start_time?: string;
      /**
       * End Time
       * Format: date-time
       */
      end_time?: string;
      /** Test Data Point Count */
      test_data_point_count?: number;
      /** Model Metrics */
      model_metrics?: any;
      /** Error Matrix */
      error_matrix?: unknown[];
      /**
       * App Link
       * @description This URL links to the Okareo webpage for this test run
       * @default
       */
      app_link?: string;
    };
    /** TestRunPayload */
    TestRunPayload: {
      /**
       * Mut Id
       * Format: uuid
       * @description ID of model
       */
      mut_id?: string;
      /**
       * Scenario Set Id
       * Format: uuid
       * @description ID of scenario set
       */
      scenario_set_id?: string;
      /**
       * Name
       * @description Name of test run
       */
      name?: string;
      /**
       * Tags
       * @description Tags are strings that can be used to filter test runs in the Okareo app
       * @default []
       */
      tags?: string[];
      /** @description The type of test run will determine which relevant model metrics should be calculated. */
      type?: components["schemas"]["TestRunType"];
      /**
       * Start Time
       * Format: date-time
       */
      start_time?: string;
      /**
       * End Time
       * Format: date-time
       */
      end_time?: string;
      /**
       * Calculate Model Metrics
       * @description Boolean value indicating if model metrics should be calculated
       * @default false
       */
      calculate_model_metrics?: boolean;
    };
    /** TestRunPayloadV2 */
    TestRunPayloadV2: {
      /**
       * Mut Id
       * Format: uuid
       * @description ID of the model
       */
      mut_id: string;
      /**
       * Api Keys
       * @description Dictionary that maps model type to the respective API keys
       */
      api_keys?: {
        [key: string]: string;
      };
      /**
       * Metrics Kwargs
       * @description Dictionary of metrics to be measured
       * @default {}
       */
      metrics_kwargs?: {
        [key: string]: number[] | string[];
      };
      /**
       * Name
       * @description Name of the test run
       */
      name?: string;
      /**
       * @description The type of test run will determine which relevant model metrics should be calculated
       * @default MULTI_CLASS_CLASSIFICATION
       */
      type?: components["schemas"]["TestRunType"];
      /**
       * Calculate Metrics
       * @description Boolean value indicating if metrics should be calculated for the test run
       * @default true
       */
      calculate_metrics?: boolean;
      /**
       * Tags
       * @description Tags are strings that can be used to filter test runs in the Okareo app
       * @default []
       */
      tags?: string[];
      /**
       * Scenario Id
       * Format: uuid
       * @description ID of the scenario set
       */
      scenario_id: string;
      /**
       * Project Id
       * Format: uuid
       * @description ID of the project
       */
      project_id?: string;
      /** Model Results */
      model_results?: any;
    };
    /**
     * TestRunType
     * @description An enumeration.
     * @enum {string}
     */
    TestRunType: "MULTI_CLASS_CLASSIFICATION" | "INFORMATION_RETRIEVAL" | "NL_GENERATION" | "invariant";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = any;

export type external = any;

export interface operations {

  /**
   * Get All Projects
   * @description Get a list of projects for this organization
   *
   * Returns:
   *     a list of requested projects
   */
  get_all_projects_v0_projects_get: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"][];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Create Project
   * @description Create a project
   *
   * Returns:
   *     the id, name, and tags for the created project
   */
  create_project_v0_projects_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get Project
   * @description Get a project
   *
   * Returns:
   *     the requested project
   */
  get_project_v0_projects__project_id__get: {
    parameters: {
      header: {
        "api-key": string;
      };
      path: {
        /** @description The ID of the project */
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Update Project
   * @description Update a project
   *
   * Returns:
   *     the requested project
   */
  update_project_v0_projects__project_id__put: {
    parameters: {
      header: {
        "api-key": string;
      };
      path: {
        /** @description ID of the project */
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get Scenario Sets
   * @description Find all scenario sets based on either the project id or the scenario id
   *
   * Returns:
   *     a list of scenario sets (project id) or a list of scenarios (scenario id)
   */
  get_scenario_sets_v0_scenario_sets_get: {
    parameters: {
      query?: {
        /** @description The ID of the scenario set */
        scenario_id?: string;
        /** @description The ID of the project */
        project_id?: string;
      };
      header: {
        "api-key": string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ScenarioSetResponse"][];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Create Scenario Set
   * @description Triggers a generation of a test scenario set, could be long running.
   * This scenario set can now be used for testing on a model.
   *
   * Returns:
   *     Object: generation result with '201 Created' status code on success.
   */
  create_scenario_set_v0_scenario_sets_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScenarioSetCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ScenarioSetResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Update Scenario Set
   * @description Update a Scenario Set
   *
   * Returns:
   *     the updated Scenario Set
   */
  update_scenario_set_v0_scenario_sets__scenario_id__put: {
    parameters: {
      header: {
        "api-key": string;
      };
      path: {
        /** @description The ID of the scenario set to modify */
        scenario_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScenarioSetUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ScenarioSetResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Delete Scenario Set
   * @description Deletes the scenario set and cascades deletes to all related entities.
   * Namely, Evaluations, Evaluation Datapoints, and  Model Datapoints
   *
   * !! Use With Caution !!
   *
   * Raises:
   *     HTTPException: 404 if scenario_id is not found
   *
   * Returns: 204 status code on successful deletion
   */
  delete_scenario_set_v0_scenario_sets__scenario_id__delete: {
    parameters: {
      query: {
        /** @description Name of the Scenario Set to delete */
        name: string;
      };
      header: {
        "api-key": string;
      };
      path: {
        /** @description The ID of the Scenario Set to delete */
        scenario_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Scenario Sets Upload
   * @description Upload new scenarios
   *
   * Returns:
   *     the Scenario Set with the uploaded scenarios
   */
  scenario_sets_upload_v0_scenario_sets_upload_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_scenario_sets_upload_v0_scenario_sets_upload_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ScenarioSetResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get Scenario Sets Download
   * @description Get the scenario set for a particular scenario ID
   *
   * Returns:
   *     a list of scenarios
   */
  get_scenario_sets_download_v0_scenario_sets_download__scenario_id__get: {
    parameters: {
      header: {
        "api-key": string;
      };
      path: {
        /** @description The ID of the scenario set */
        scenario_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get Scenario Set Data Points
   * @description Get all scenarios datapoints
   *
   * Returns:
   *     a list of scenario datapoints
   */
  get_scenario_set_data_points_v0_scenario_data_points__scenario_id__get: {
    parameters: {
      header: {
        "api-key": string;
      };
      path: {
        /** @description The ID of the scenario set to download */
        scenario_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ScenarioDataPoinResponse"][];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Generate Scenario Set
   * @description Triggers a generation of a scenario set based on source scenario ID, could be long running.
   * A registered model can now use this scenario set for testing.
   *
   * Returns:
   *     Object: generation result with '201 Created' status code on success.
   */
  generate_scenario_set_v0_scenario_sets_generate_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScenarioSetGenerate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ScenarioSetResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get Datapoints
   * @description gets all the datapoints created by a given token.
   *
   * Returns:
   *     list: An array of datapoint objects.
   */
  get_datapoints_v0_find_datapoints_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DatapointSearch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DatapointListItem"][];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Add Datapoint
   * @description Add a datapoint for a particular registered model
   *
   * Returns:
   *     Empty ressponse with 201 status code on success.
   */
  add_datapoint_v0_datapoints_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DatapointSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["DatapointResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Register Model
   * @description Register a model for testing. This model can then be tested using a scenario set.
   *
   * Returns:
   *     the id of the registered model
   */
  register_model_v0_register_model_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModelUnderTestSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ModelUnderTestResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get Model Under Test
   * @description Get a model under test
   *
   * Returns:
   *     the requested model under test
   */
  get_model_under_test_v0_models_under_test__mut_id__get: {
    parameters: {
      header: {
        "api-key": string;
      };
      path: {
        /** @description The ID of the model */
        mut_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ModelUnderTestResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Update Model Under Test
   * @description Update a model under test
   *
   * Returns:
   *     the updated model under test
   */
  update_model_under_test_v0_models_under_test__mut_id__put: {
    parameters: {
      header: {
        "api-key": string;
      };
      path: {
        /** @description The ID of the model under test */
        mut_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModelUnderTestSchema"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ModelUnderTestResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get All Models Under Test
   * @description Get a list of models under test for this organization
   *
   * Returns:
   *     a list of requested models under test
   */
  get_all_models_under_test_v0_models_under_test_get: {
    parameters: {
      query?: {
        /** @description The ID of the project */
        project_id?: string;
      };
      header: {
        "api-key": string;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ModelUnderTestResponse"][];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get Semantic Overlap */
  get_semantic_overlap_v0_get_semantic_overlap_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SemanticPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SemanticResult"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Find Test Run
   * @description Find Test Runs
   *
   * Returns:
   *     a list of Test Runs
   */
  find_test_run_v0_find_test_runs_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeneralFindPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TestRunItem"][];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get Test Run
   * @description Get a Test Run
   *
   * Returns:
   *     the Test Run
   */
  get_test_run_v0_test_runs__test_run_id__get: {
    parameters: {
      header: {
        "api-key": string;
      };
      path: {
        /** @description ID of test run */
        test_run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TestRunItem"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Update Test Run
   * @description Update a Test Run
   * Returns:
   *     the updated Test Run
   */
  update_test_run_v0_test_runs__test_run_id__put: {
    parameters: {
      header: {
        "api-key": string;
      };
      path: {
        /** @description The ID of the test run to modify */
        test_run_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TestRunPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TestRunItem"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Run Test
   * @description Runs tests on a model (mut_id) using previously generated scenario.
   * Feeds the scenario data (scenario_id) into the model and evaulates results
   * depending on the test type specified.
   *
   * Returns:
   *     The test run data which includes the evaluated metrics from the run.
   */
  run_test_v0_test_run_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TestRunPayloadV2"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TestRunItem"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Add Test Data Point
   * @description Add a test run metric
   *
   * Returns:
   *     The persisted test run metric item
   */
  add_test_data_point_v0_test_data_point_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TestDataPointPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TestDataPointResponse"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get Test Data Point
   * @description Get a Test Run
   *
   * Returns:
   *     the Test Run
   */
  get_test_data_point_v0_test_data_points__test_data_point_id__get: {
    parameters: {
      header: {
        "api-key": string;
      };
      path: {
        /** @description The ID of the test data point to return */
        test_data_point_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TestDataPointItem"];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Find Test Data Points
   * @description Find Test Data Point
   *
   * Returns:
   *     a list of Test Data Points
   */
  find_test_data_points_v0_find_test_data_points_post: {
    parameters: {
      header: {
        "api-key": string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FindTestDataPointPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TestDataPointItem"][];
        };
      };
      /** @description Input data is incorrect */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Data is not found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Input data is invalid */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
