name: Release SDK
env:
  SKIP_YARN_COREPACK_CHECK: true
  SDK_BUILD_ID: ${{ github.run_number }}
  OKAREO_API_KEY: ${{ secrets.OKAREO_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "21.4.0"
          cache: "yarn"

      - name: Enable corepack
        run: |
          corepack enable
          corepack prepare yarn@4.0.1 --activate
          yarn set version 4.0.1
        
      - name: Install Dependencies
        run: yarn install

      - name: Publish SDK
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}



